
ALTER PROC [DBO].[USP_PRODUCT](@IP1 INT,@IP2 VARCHAR(50))
AS
BEGIN
	BEGIN TRY
		IF  EXISTS(SELECT 1 FROM PRODUCTION.PRODUCT WHERE PRODUCTID=@IP1 )
		BEGIN
			IF LEN(@IP2)>=3 AND LEN(@IP2)<=15
			BEGIN
				UPDATE PRODUCTION.PRODUCT SET NAME=@IP2,MODIFIEDDATE=GETDATE() WHERE PRODUCTID=@IP1 ;
			END 
			ELSE
			RETURN -2
		END
		ELSE
		RETURN -1
	END TRY
	BEGIN CATCH
		RETURN -99
	END CATCH

END